import "./globals.css";
import { ThemeProvider } from "next-themes";
import LocomotiveScrollProvider from "@/components/LocomotiveScrollProvider";

export const metadata = {
  title: "KodingMonk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-xl font-Comic_Neue bg-black text-white">
        <ThemeProvider attribute="class" className="">
          <LocomotiveScrollProvider>
            {children}
          </LocomotiveScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
