import "./globals.css";
import { ThemeProvider } from 'next-themes'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="text-xl font-Comic_Neue bg-black text-white">
          <ThemeProvider attribute="class" className="">
            <Navbar/>
            {children}
            <Footer/>
          </ThemeProvider>
        </body>
    </html>
  );
}
